Load idna encoding before running any CLI code
There's a reported issue on py36 MSI installs
of the CLI where you'll occasionally see idna LookupErrors.

```
Traceback (most recent call last):
  File ".\runtime\lib\site-packages\botocore\httpsession.py", line 258, in send
    decode_content=False,
  File ".\runtime\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File ".\runtime\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File ".\runtime\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File ".\runtime\lib\site-packages\urllib3\connection.py", line 301, in connect
    conn = self._new_conn()
  File ".\runtime\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File ".\runtime\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "socket.py", line 743, in getaddrinfo
LookupError: unknown encoding: idna
```

There appears to be some sort of race condition where
worker threads aren't able to find this encoding.  Ensuring
the encoding is used before any CLI code will prevent this
issue.

Note that we're encoding a string instead of just importing
the apropriate module to ensure the encoding is registered with
the codecs registry.  Encoding a string will implicitly import the
`encodings.idna` module:

```
>>> import sys
>>> [m for m in sys.modules if m.startswith('encodings.')]
['encodings.aliases', 'encodings.utf_8', 'encodings.latin_1']
>>> u''.encode('idna')
b''
>>> [m for m in sys.modules if m.startswith('encodings.')]
['encodings.aliases', 'encodings.utf_8', 'encodings.latin_1', 'encodings.idna']
```

See: https://bugs.python.org/issue29288