Update API version of ExecCredential to v1
This is because the kubeconfig generated by `kubectl` 1.24 (released 3rd May) no longer supports `client.authentication.k8s.io/v1alpha1` version and fails with:
```
error: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

This commit is more or less a naive search&replace. Some tests may be failing so more changes may be needed.